<?php return array(
    'root' => array(
        'name' => 'drupal/legacy-project',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'asm89/stack-cors' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'b9c31def6a83f84b4d4a40d35996d375755f0e08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chi-teck/drupal-code-generator' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'reference' => '22ed1cc02dc47814e8239de577da541e9b9bd980',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chi-teck/drupal-code-generator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => '3953f23262f2bff1919fc82183ad9acb13ff62c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '4.10.4',
            'version' => '4.10.4.0',
            'reference' => '69d29da4acac31a43caa4cea13b6b948f4e5c56d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/config' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => '597f8d7fbeef801736250ec10c3e190569b1b0ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/config',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/filter-via-dot-access-data' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'f9e84bc623d420120028a50dcb9b1d4609ae3b5f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/filter-via-dot-access-data',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/log' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '3ad08dc57e8aff9400111bad36beb0ed387fe6a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/log',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'dfc464c4d4a47594cac5eac01ce265e04b70cb94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/robo' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => 'ccf80963abf11bdb8e90659aa99a7449b21e9452',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/robo',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/self-update' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '972a1016761c9b63314e040836a12795dff6953a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/self-update',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/site-alias' => array(
            'pretty_version' => '4.1.2',
            'version' => '4.1.2.0',
            'reference' => 'd92058201fc8475a33fb9a2b80ffe5c89472f5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-alias',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/site-process' => array(
            'pretty_version' => '4.2.1',
            'version' => '4.2.1.0',
            'reference' => 'ee3bf69001694b2117cc2f96c2ef70d8d45f1234',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-process',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.13.3',
            'version' => '1.13.3.0',
            'reference' => '648b0343343565c4a056bfc8392201385e8d89f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/reflection' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '6bcea3e81ab8b3d0abe5fde5300bbc8a968960c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/reflection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core' => array(
            'pretty_version' => '9.5.11',
            'version' => '9.5.11.0',
            'reference' => '8afcb233c2a71501b35fed2713167c37831d5c19',
            'type' => 'drupal-core',
            'install_path' => __DIR__ . '/../../core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-annotation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-assertion' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-class-finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-composer-scaffold' => array(
            'pretty_version' => '9.5.11',
            'version' => '9.5.11.0',
            'reference' => '08da8e59c6f1bd0b1a58d18f8addc0d937bbacc7',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-composer-scaffold',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-datetime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-diff' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-discovery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-file-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-file-security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-front-matter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-gettext' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-graph' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-php-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-plugin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-project-message' => array(
            'pretty_version' => '9.5.11',
            'version' => '9.5.11.0',
            'reference' => '5dfa0b75a057caf6542be67f61e7531c737db48c',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-project-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-proxy-builder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-recommended' => array(
            'pretty_version' => '9.5.11',
            'version' => '9.5.11.0',
            'reference' => 'af3521be5376e333ddcdbd31c5a169f16423b46f',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-render' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-serialization' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-transliteration' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/core-vendor-hardening' => array(
            'pretty_version' => '9.5.11',
            'version' => '9.5.11.0',
            'reference' => '8293a845c64f1faad0d44955611f8cce69320274',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-vendor-hardening',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-version' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '9.5.11',
            ),
        ),
        'drupal/gin' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '8.x-3.1',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../themes/contrib/gin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/gin_toolbar' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '8.x-1.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../modules/contrib/gin_toolbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/legacy-project' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/phpexcel' => array(
            'pretty_version' => '4.0.0-beta3',
            'version' => '4.0.0.0-beta3',
            'reference' => '4.0.0-beta3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../modules/contrib/phpexcel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/stripe' => array(
            'pretty_version' => '2.0.0-beta4',
            'version' => '2.0.0.0-beta4',
            'reference' => '2.0.0-beta4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../modules/contrib/stripe',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drush/drush' => array(
            'pretty_version' => '11.6.0',
            'version' => '11.6.0.0',
            'reference' => 'f301df5dec8d2aacb03d3e01e0ffc6d98e10ae78',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drush/drush',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.2.6',
            'version' => '3.2.6.0',
            'reference' => 'e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'enlightn/security-checker' => array(
            'pretty_version' => 'v1.11.0',
            'version' => '1.11.0.0',
            'reference' => '68df5c7256c84b428bf8fcff0d249de06ce362d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../enlightn/security-checker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.19.0',
            'version' => '4.19.0.0',
            'reference' => 'b287d2a16aceffbf6e0295559b39662612b77fcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grasmash/expander' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'b7cbc1f2fdf9a9c0e253a424c2a4058316b7cb6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/expander',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.8',
            'version' => '6.5.8.0',
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => '67ab6e18aaa14d753cc148911d273f6e6cb6721e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'e4490cabc77465aaee90b20cfc9a770f8c04be6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kint-php/kint' => array(
            'pretty_version' => '5.1.1',
            'version' => '5.1.1.0',
            'reference' => '8c5ec370c3382ceae0b88e91f9bbb00e6bb4f93b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kint-php/kint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laminas/laminas-diactoros' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '2.18.1',
            ),
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.18.0',
            'version' => '2.18.0.0',
            'reference' => '06f211dfffff18d91844c1f55250d5d13c007e18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-feed' => array(
            'pretty_version' => '2.26.0',
            'version' => '2.26.0.0',
            'reference' => '76f537d457bace6d57aa483fccfc676198d5fca7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-feed',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.21.0',
            'version' => '3.21.0.0',
            'reference' => 'b1c81514cfe158aadf724c42b34d3d0a8164c096',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.5',
            'version' => '4.2.5.0',
            'reference' => 'd3cebb0ff4685ff61c749e54b27db49319e2ec00',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'longwave/laminas-diactoros' => array(
            'pretty_version' => '2.14.3',
            'version' => '2.14.3.0',
            'reference' => '2bd6b47a090ae924ecc298657d01f8a462f7507b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../longwave/laminas-diactoros',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '682f1098a8fddbaf43edac2306a691c7ad508ec5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.6',
            'version' => '2.7.6.0',
            'reference' => '897eb517a343a2281f11bc5556d6548db7d93947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.7.0',
            'version' => '5.7.0.0',
            'reference' => 'dca41cd15c2ac9d055ad70dbfd011130757d1f82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'orno/di' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'pear/archive_tar' => array(
            'pretty_version' => '1.4.14',
            'version' => '1.4.14.0',
            'reference' => '4d761c5334c790e45ef3245f0864b8955c562caa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/archive_tar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.17',
            'version' => '1.10.17.0',
            'reference' => 'c7b55789d01de0ce090d289b73f1bbd6a2f113b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/math' => array(
            'pretty_version' => '0.3.0',
            'version' => '0.3.0.0',
            'reference' => 'fc31c8f57a7a81f962cbf389fd89f4d9d06fc99a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.30.2',
            'version' => '1.30.2.0',
            'reference' => '09cdde5e2f078b9a3358dd217e2c8cb4dac84be2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpword' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '6d75328229bc93790b37e93741adf70646cea958',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpword',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '^1.0',
            ),
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.12.18',
            'version' => '0.12.18.0',
            'reference' => 'ddff0ac01beddc251786fe70367cd8bbdb258196',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.17',
            ),
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'stack/builder' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => 'a4faaa6f532c6086bc66c29e1bc6c29593e1ca7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stack/builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v7.128.0',
            'version' => '7.128.0.0',
            'reference' => 'c704949c49b72985c76cc61063aa26fefbd2724e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony-cmf/routing' => array(
            'pretty_version' => '2.3.4',
            'version' => '2.3.4.0',
            'reference' => 'bbcdf2f6301d740454ba9ebb8adaefd436c36a6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony-cmf/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'reference' => '33fa45ffc81fdcc1ca368d4946da859c8cdb58d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'reference' => '1a692492190773c5310bc7877cb590c04c2f05be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'reference' => '9065fe97dbd38a897e95ea254eb5ddfe1310f734',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.4',
            'version' => '2.5.4.0',
            'reference' => '605389f2a7e5625f273b53960dc46aeaf9c62918',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'reference' => 'be731658121ef2d8be88f3a1ec938148a9237291',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'reference' => '1e866e9e5c1b22168e0ce5f0b467f19bba61266a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v1.1.13',
            'version' => '1.1.13.0',
            'reference' => '1d5cd762abaa6b2a4169d3e77610193a7157129e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.4.30',
            'version' => '6.4.30.0',
            'reference' => '441c6b69f7222aadae7cbf5df588496d5ee37789',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.4.31',
            'version' => '6.4.31.0',
            'reference' => '5547f2e1f0ca8e2e7abe490156b62da778cfbe2b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v2.5.5',
            'version' => '2.5.5.0',
            'reference' => '48ef1d0a082885877b664332b9427662065a360c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v4.4.49',
            'version' => '4.4.49.0',
            'reference' => '191413c7b832c015bb38eae963f2e57498c3c173',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v4.4.51',
            'version' => '4.4.51.0',
            'reference' => 'ad8ab192cb619ff7285c95d28c69b36d718416c7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v5.4.13',
            'version' => '5.4.13.0',
            'reference' => 'bb2ccf759e2b967dcd11bdee5bdf30dddd2290bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '927013f3aac555983a5059aada98e1907d842695',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '380872130d3a5dd3ace2f4010d95125fde5d5c70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => 'fa2ae56c44f03bed91a39bfc9822e31e7c5c38ce',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '0f68c03565dcaaf25a890667542e8bd75fe7e5bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'reference' => '5cee9cdc4f7805e2699d9fd66991a0e6df8252a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v2.1.4',
            'version' => '2.1.4.0',
            'reference' => 'a125b93ef378c492e274f217874906fb9babdebb',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v4.4.44',
            'version' => '4.4.44.0',
            'reference' => 'f7751fd8b60a07f3f349947a309b5bdfce22d6ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'reference' => '6e01d63c55657930a6de03d6e36aae50af98888d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v2.5.4',
            'version' => '2.5.4.0',
            'reference' => 'f37b419f7aea2e9abf10abd261832cace12e3300',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.4.30',
            'version' => '6.4.30.0',
            'reference' => '50590a057841fa6bf69d12eceffce3465b9e32cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v4.4.47',
            'version' => '4.4.47.0',
            'reference' => '45036b1d53accc48fe9bab71ccd86d57eba0dd94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v2.5.4',
            'version' => '2.5.4.0',
            'reference' => '450d4172653f38818657022252f9d81be89ee9a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v4.4.48',
            'version' => '4.4.48.0',
            'reference' => '54781a4c41efbd283b779110bf8ae7f263737775',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v5.4.48',
            'version' => '5.4.48.0',
            'reference' => '42f18f170aa86d612c3559cfb3bd11a375df32c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v4.4.45',
            'version' => '4.4.45.0',
            'reference' => 'aeccc4dc52a9e634f1d1eebeb21eacfdcff1053d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v2.15.6',
            'version' => '2.15.6.0',
            'reference' => 'ad637405a828601a56f32ccab9a85541c4b66c9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typo3/phar-stream-wrapper' => array(
            'pretty_version' => 'v3.1.8',
            'version' => '3.1.8.0',
            'reference' => 'a931b28f422a60052db85c0a84a05a366453b2c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typo3/phar-stream-wrapper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webflo/drupal-finder' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '73045060b0894c77962a10cff047f72872d8810c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webflo/drupal-finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
